package com.mdasadullahmaruf.latos

import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.content.pm.ResolveInfo
import android.util.Log
import java.util.Locale

object PackageMapper {

    private val TAG = "LatOS_PackageMapper"

    private var cachedApps: List<Pair<String, String>>? = null
    private var cacheTimestamp: Long = 0
    private val CACHE_TTL = 5 * 60 * 1000

    private val knownApps = mapOf(
        "google" to "com.google.android.googlequicksearchbox",
        "google search" to "com.google.android.googlequicksearchbox",
        "youtube" to "com.google.android.youtube",
        "youtube music" to "com.google.android.apps.youtube.music",
        "gmail" to "com.google.android.gm",
        "google maps" to "com.google.android.apps.maps",
        "maps" to "com.google.android.apps.maps",
        "google drive" to "com.google.android.apps.docs",
        "drive" to "com.google.android.apps.docs",
        "google photos" to "com.google.android.apps.photos",
        "photos" to "com.google.android.apps.photos",
        "google meet" to "com.google.android.apps.meetings",
        "meet" to "com.google.android.apps.meetings",
        "google calendar" to "com.google.android.calendar",
        "calendar" to "com.google.android.calendar",
        "google translate" to "com.google.android.apps.translate",
        "translate" to "com.google.android.apps.translate",
        "play store" to "com.android.vending",
        "google play" to "com.android.vending",
        "google play store" to "com.android.vending",
        "app store" to "com.android.vending",
        "gemini" to "com.google.android.apps.bard",
        "google gemini" to "com.google.android.apps.bard",
        "chrome" to "com.android.chrome",
        "google chrome" to "com.android.chrome",
        "google assistant" to "com.google.android.googlequicksearchbox",
        "whatsapp" to "com.whatsapp",
        "instagram" to "com.instagram.android",
        "facebook" to "com.facebook.katana",
        "messenger" to "com.facebook.orca",
        "facebook messenger" to "com.facebook.orca",
        "twitter" to "com.twitter.android",
        "x" to "com.twitter.android",
        "snapchat" to "com.snapchat.android",
        "tiktok" to "com.zhiliaoapp.musically",
        "linkedin" to "com.linkedin.android",
        "telegram" to "org.telegram.messenger",
        "discord" to "com.discord",
        "signal" to "org.thoughtcrime.securesms",
        "pinterest" to "com.pinterest",
        "reddit" to "com.reddit.frontpage",
        "threads" to "com.instagram.barcelona",
        "phone" to "com.google.android.dialer",
        "dialer" to "com.google.android.dialer",
        "contacts" to "com.google.android.contacts",
        "messages" to "com.google.android.apps.messaging",
        "message" to "com.google.android.apps.messaging",
        "sms" to "com.google.android.apps.messaging",
        "gallery" to "com.vivo.gallery",
        "albums" to "com.vivo.gallery",
        "browser" to "com.vivo.browser",
        "calculator" to "com.vivo.calculator",
        "camera" to "com.android.camera",
        "clock" to "com.android.deskclock",
        "alarm" to "com.android.deskclock",
        "file manager" to "com.android.filemanager",
        "files" to "com.android.filemanager",
        "music" to "com.android.bbkmusic",
        "settings" to "com.android.settings",
        "weather" to "com.vivo.weather",
        "notes" to "com.vivo.notes",
        "recorder" to "com.vivo.soundrecorder",
        "compass" to "com.vivo.compass",
        "easyshare" to "com.vivo.easyshare",
        "tips" to "com.vivo.Tips",
        "vivo store" to "com.vivo.website",
        "v-appstore" to "com.vivo.appstore",
        "simple view" to "com.vivo.simplelauncher",
        "smart remote" to "com.vivo.vhome",
        "digital wellbeing" to "com.google.android.apps.wellbeing",
        "netflix" to "com.netflix.mediaclient",
        "spotify" to "com.spotify.music",
        "hotstar" to "in.startv.hotstar",
        "disney" to "in.startv.hotstar",
        "disney hotstar" to "in.startv.hotstar",
        "prime video" to "com.amazon.avod.thirdpartyclient",
        "amazon prime" to "com.amazon.avod.thirdpartyclient",
        "amazon" to "com.amazon.mShop.android.shopping",
        "mx player" to "com.mxtech.videoplayer.ad",
        "vlc" to "org.videolan.vlc",
        "zoom" to "us.zoom.videomeetings",
        "teams" to "com.microsoft.teams",
        "microsoft teams" to "com.microsoft.teams",
        "outlook" to "com.microsoft.office.outlook",
        "slack" to "com.Slack",
        "notion" to "notion.id",
        "claude" to "com.anthropic.claude",
        "chatgpt" to "com.openai.chatgpt",
        "brave" to "com.brave.browser",
        "opera" to "com.opera.browser",
        "firefox" to "org.mozilla.firefox",
        "edge" to "com.microsoft.emmx",
        "flipkart" to "com.flipkart
